services:
  prometheus:
    image: prom/prometheus:v2.53.1
    container_name: prometheus
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana:11.1.0
    container_name: grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana

  novo-pecas-online-db:
    image: postgres:17-alpine
    container_name: novo-pecas-online-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: usuario
      POSTGRES_PASSWORD: senha
      POSTGRES_DB: meubanco
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  novo-pecas-online-backend:
    image: randintn/novo-pecas-online:0.1.1
    container_name: novo-pecas-online-backend
    restart: unless-stopped
    environment:
      SPRING_PROFILES_ACTIVE: prod
    ports:
      - "8080:8080"

volumes:
  postgres_data:
  grafana_data:
