services:
  # Infrastructure
  db:
    image: postgres:17-alpine
    container_name: pecas-db-local
    restart: unless-stopped
    environment:
      POSTGRES_USER: usuario
      POSTGRES_PASSWORD: senha
      POSTGRES_DB: meubanco
    ports:
      - "5432:5432"
    volumes:
      - postgres_local_data:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    container_name: pecas-redis-local
    restart: unless-stopped
    command: [ "redis-server", "--requirepass", "Backtalk1-Anyplace5-Magnolia8-Refute6-Coke7" ]
    ports:
      - "6379:6379"

  # Monitoring Stack
  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.107.0
    container_name: pecas-otel-local
    restart: unless-stopped
    command: [ "--config=/etc/otelcol-contrib/config.yml" ]
    ports:
      - "4317:4317" # OTLP gRPC
      - "4318:4318" # OTLP HTTP
    volumes:
      - ./monitoring/otel-collector-config.yml:/etc/otelcol-contrib/config.yml

  prometheus:
    image: prom/prometheus:v2.53.1
    container_name: pecas-prometheus-local
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - otel-collector

  tempo:
    image: grafana/tempo:2.2.0
    container_name: pecas-tempo-local
    command: [ "-config.file=/etc/tempo.yml" ]
    volumes:
      - ./monitoring/tempo.yml:/etc/tempo.yml
    ports:
      - "3200:3200"
    restart: unless-stopped

  grafana:
    image: grafana/grafana:11.1.0
    container_name: pecas-grafana-local
    restart: unless-stopped
    environment:
      - GF_SECURITY_ALLOW_EMBEDDING=true
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    ports:
      - "3000:3000"
    volumes:
      - grafana_local_data:/var/lib/grafana
      - ./monitoring/datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml
      - ./monitoring/dashboards.yml:/etc/grafana/provisioning/dashboards/dashboards.yml
      - ./grafana-dashboard.json:/etc/grafana/provisioning/dashboards/main-dashboard.json
    depends_on:
      - prometheus
      - tempo

volumes:
  postgres_local_data:
  grafana_local_data:
