spring:
  application:
    name: novo-pecas-online
  datasource:
    url: jdbc:postgresql://backend.pecasonlinex.com.br:5432/meubanco
    driver-class-name: org.postgresql.Driver
    username: novo-pecas-online_owner
    password: cKkerHWVgX94
  mail:
    enabled: true
    host: smtp.gmail.com
    port: 587
    username: pecas.online.agora@gmail.com
    # Use a app password gerada no Gmail
    password: qkts eacj hcek zxwh
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
        imap:
          host: imap.gmail.com
          port: 993
          ssl.enable: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
    imap:
      enabled: true
      inbox-folder: INBOX
      processed-folder: Processed
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    operationsSorter: method
    tagsSorter: method
logging:
  level:
    org:
      pecasonline:
        features:
          stock:
            StockService: INFO
server:
  forward-headers-strategy: native

app:
  url: ${CURRENT_URL:}

asaas:
  api:
    api-key: ${ASAAS_API_KEY:REDACTED_ASAAS_KEY}
    base-url: https://sandbox.asaas.com/api/v3