spring:
  datasource:
#    url: jdbc:postgresql://localhost:5432/novo-pecas-online?currentSchema=public
    url: jdbc:postgresql://backend.pecasonlinex.com.br:5432/meubanco
    driver-class-name: org.postgresql.Driver
    username: usuario
    password: senha
  logging:
    level:
      org.pecasonline: DEBUG
      root: DEBUG
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  h2:
    console:
      enabled: false
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  flyway:
    baseline-on-migrate: true
  mail:
    enabled: false
    host: smtp.gmail.com
    port: 587
    username: pecas.online.agora@gmail.com
    # Use a app password gerada no Gmail
    password: qkts eacj hcek zxwh
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
        imap:
          host: imap.gmail.com
          port: 993
          ssl.enable: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
    imap:
      enabled: true
      inbox-folder: INBOX
      processed-folder: Processed

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    operationsSorter: method
    tagsSorter: method

app:
  url: ${CURRENT_URL:}

asaas:
  api:
    api-key: ${ASAAS_API_KEY:$aact_MzkwODA2MWY2OGM3MWRlMDU2NWM3MzJlNzZmNGZhZGY6OmVhY2UzOTA2LTg3ZmYtNDcyMy1hNmViLWY3MGM2MTlmY2E0NTo6JGFhY2hfMWUzZjcwMmYtYzU5Yi00OTAyLTk1NjMtNmQ1OTYwMGE4NTYy}
    base-url: https://sandbox.asaas.com/api/v3