spring:
  application:
    name: novo-pecas-online
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    operationsSorter: method
    tagsSorter: method
logging:
  level:
    org:
      pecasonline:
        features:
          stock:
            StockService: DEBUG
server:
  forward-headers-strategy: native