spring:
  application:
    name: novo-pecas-online
  datasource:
    url: jdbc:postgresql://ep-wandering-mouse-a5jp4pxe.us-east-2.aws.neon.tech/novo-pecas-online?user=novo-pecas-online_owner&password=cKkerHWVgX94&sslmode=require
    driver-class-name: org.postgresql.Driver
    username: novo-pecas-online_owner
    password: cKkerHWVgX94
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  mail:
    enabled: true
    host: smtp.gmail.com
    port: 587
    username: pecas.online.agora@gmail.com
    # Use a app password gerada no Gmail
    password: qkts eacj hcek zxwh
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
        imap:
          host: imap.gmail.com
          port: 993
          ssl.enable: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
    imap:
      enabled: true
      inbox-folder: INBOX
      processed-folder: Processed
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    operationsSorter: method
    tagsSorter: method
logging:
  level:
    org:
      pecasonline:
        features:
          stock:
            StockService: INFO
server:
  forward-headers-strategy: native

app:
  url: ${CURRENT_URL:}

asaas:
  api:
    sandbox-base-url: https://sandbox.asaas.com/api/v3
    production-base-url: https://api.asaas.com/v3
    environment: ${ASAAS_ENV_SELECTOR:sandbox}
    api-key: ${ASAAS_API_KEY:$aact_MzkwODA2MWY2OGM3MWRlMDU2NWM3MzJlNzZmNGZhZGY6OjVmNjY1YzM3LTlkMjMtNGI1OS1hY2ZjLTk0ZTg1OTA0OTRhODo6JGFhY2hfYThlZDE3ZjQtYzc2Ni00OGQ2LWIwZmUtZjE3ODkwNzIzZmYz}
