spring:
  application:
    name: novo-pecas-online
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  mail:
    enabled: false
  jpa:
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          batch_size: 10000
        order_inserts: true
        order_updates: true
  threads:
    virtual:
      enabled: true
app:
  url: ${CURRENT_URL:}
  site_url: ${SITE_URL:https://www.pecasonlinex.com.br}


