spring:
  datasource:
    url: jdbc:postgresql://backend.pecasonlinex.com.br:5432/meubanco
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME:}
    password: ${DB_PASSWORD:}
  logging:
    level:
      pecasonline: DEBUG
      org.pecasonline: DEBUG
      root: DEBUG
  h2:
    console:
      enabled: false
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  flyway:
    baseline-on-migrate: true
  mail:
    enabled: false
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME:}
    # Use a app password gerada no Gmail
    password: ${MAIL_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
        imap:
          host: imap.gmail.com
          port: 993
          ssl.enable: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
    imap:
      enabled: true
      inbox-folder: INBOX
      processed-folder: Processed

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    operationsSorter: method
    tagsSorter: method

app:
  url: ${CURRENT_URL:}

asaas:
  api:
    api-key: ${ASAAS_API_KEY:}
    base-url: https://sandbox.asaas.com/api/v3